Cookbook.destroy_all
Recipe.destroy_all
User.destroy_all

u1 = User.create(username: 'Goku', password: '1234', avatar: 'https://pbs.twimg.com/profile_images/1366466342354751491/JyhZpbtu_400x400.jpg')
u2 = User.create(username: 'Naruto', password: 'abc', avatar: 'https://static.wikia.nocookie.net/naruto/images/0/09/Naruto_newshot.png/revision/latest?cb=20210223094656')

Recipe.create(name: 'Kimchi Fried Rice', category: 'Pork', origin: 'South Korea', instructions: 'Dice up all ingredients. Fry pork, then add kimchi and other veg. Then add rice and stir everything.', ingredient1: 'pork', ingredient2: 'kimchi', ingredient3: 'onion', ingredient4: '', ingredient5: '', ingredient6: '', ingredient7: '', ingredient8: '', ingredient9: '', ingredient10: '', ingredient11: '', ingredient12: '', ingredient13: '', ingredient14: '', ingredient15: '', ingredient16: '', ingredient17: '', ingredient18: '', ingredient19: '', ingredient20: '', measurement1: '100g', measurement2: 'half cup', measurement3: 'half cup', measurement4: '', measurement5: '', measurement6: '', measurement7: '', measurement8: '', measurement9: '', measurement10: '', measurement11: '', measurement12: '', measurement13: '', measurement14: '', measurement15: '', measurement16: '', measurement17: '', measurement18: '', measurement19: '', measurement20: '', image:'https://static01.nyt.com/images/2021/01/17/dining/kimchi-rice/merlin_181989396_094243fb-1b13-4117-aeaa-d413d5a1dd8c-articleLarge.jpg')
Recipe.create(name: 'Instant Ramen', category: 'Soup', origin: 'Japan', instructions: 'add powder and veg to noodles, then add hot water, wait for 3 minutes, and done.', ingredient1: 'powder', ingredient2: 'noodle', ingredient3: 'veg', ingredient4: 'water', ingredient5: '', ingredient6: '', ingredient7: '', ingredient8: '', ingredient9: '', ingredient10: '', ingredient11: '', ingredient12: '', ingredient13: '', ingredient14: '', ingredient15: '', ingredient16: '', ingredient17: '', ingredient18: '', ingredient19: '', ingredient20: '', measurement1: '1pack', measurement2: '1pack', measurement3: '1pack', measurement4: '500g', measurement5: '', measurement6: '', measurement7: '', measurement8: '', measurement9: '', measurement10: '', measurement11: '', measurement12: '', measurement13: '', measurement14: '', measurement15: '', measurement16: '', measurement17: '', measurement18: '', measurement19: '', measurement20: '', image: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Mama_instant_noodle_block.jpg')

Cookbook.create(user_id: u1.id, recipe_id: Recipe.all.sample.id)
Cookbook.create(user_id: u2.id, recipe_id: Recipe.all.sample.id)